# Solely for requirements.txt.
load("@rules_python//experimental/python:wheel.bzl", "py_package")

package(default_visibility = ["//visibility:public"])

py_package(
    name = "c7n_gcp_pkg",
    # Only include these Python packages.
    deps = [
        "c7n_gcp",
    ],
)
