load("@rules_python//python:defs.bzl", "py_library")

package(default_visibility = ["//visibility:private"])

py_library(
    name = "provisioning",
    srcs = glob(["*.py"]),
    visibility = ["//visibility:public"],
)
