name: Bazel build docs
on: [pull_request]

jobs:
#      - name: Run a container with the image
#        run: docker run -dit -v /tmp/output_build:/tmp/output_build --name baz my-baz
#      - name: Execute bazel build //tools/c7n_sphinxext/c7n_sphinxext:sphinx_gen
#        run: |
#          docker exec -t baz bazel --output_user_root=/tmp/output_build build //tools/c7n_sphinxext/c7n_sphinxext:sphinx_gen
#          sudo find /tmp/output_build/ -name 'html' -exec cp -n -at /tmp {} +
  sphinxext_gen:
    runs-on: ubuntu-18.04
    name: Build (c7n_sphinxext)
    container:
      image: johnybear/ubuntu_c7n_cov_bazel:latest
      volumes:
        - /tmp/output_build:/tmp/output_build
        - /home/runner/.cache:/root/.cache
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Mount pip cache
        uses: actions/cache@v1
        with:
          path: "/home/runner/.cache/pip"
          key: pip
      - name: Mount bazel cache
        uses: actions/cache@v1
        with:
          path: "/home/runner/.cache/bazel"
          key: bazel
      - name: Execute bazel build //tools/c7n_sphinxext/c7n_sphinxext:sphinx_gen
        run: bazel --output_user_root=/tmp/output_build build //tools/c7n_sphinxext/c7n_sphinxext:sphinx_gen
      - name: Collect HTML docs
        run: find /tmp/output_build/ -name 'html' -exec cp -n -at /tmp {} +
      - name: Upload docs into artifacts
        uses: actions/upload-artifact@v1
        with:
          name: Html docs
          path: /tmp/html

