name: Bazel build docs
on: [pull_request]

jobs:
  sphinxext_gen:
    runs-on: ubuntu-18.04
    name: Build (c7n_sphinxext)
    container:
      image: johnybear/ubuntu_for_c7n_bazel:latest
      volumes:
        - /tmp/output_build:/tmp/output_build
        - /tmp/C7N-cov:/tmp/C7N-cov
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache deps
        id: cache-deps
        uses: actions/cache@v1
        with:
          path: /tmp/output_build
          key: output_build
      - name: Execute bazel build //tools/c7n_sphinxext/c7n_sphinxext:sphinx_gen
        run: bazel --output_user_root=/tmp/output_build build //tools/c7n_sphinxext/c7n_sphinxext:sphinx_gen
      - name: Collect output html files
        run: find /tmp/output_build/ -name 'html' -exec cp -n -at /tmp {} +
      - name: Upload docs into artifacts
        uses: actions/upload-artifact@v1
        with:
          name: Html docs
          path: /tmp/html
