name: Bazel build wheels
on: [pull_request]

jobs:
  c7n_wheel:
    runs-on: ubuntu-18.04
    name: Build (c7n_wheel)
    container:
      image: rushrecon/bazel2py:3.0.0
      volumes:
        - /tmp/output_build:/tmp/output_build
        - /tmp/out:/tmp/out
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Mount cache
        uses: actions/cache@v1
        with:
          path: "/tmp/output_build"
          key: bazel-cache
      - name: Execute bazel build c7n_wheel
        run: bazel --output_user_root=/tmp/output_build build c7n_wheel
      - name: Collect HTML docs
        run: find /tmp/output_build/ -name 'c7n*.whl' -exec cp -n -at /tmp/out {} +
      - name: Testing builded wheel
        run: pip3 install /tmp/out/*.whl
      - name: Upload docs into artifacts
        uses: actions/upload-artifact@v1
        with:
          name: c7n_wheel
          path: /tmp/out
  c7n_azure_wheel:
    runs-on: ubuntu-18.04
    name: Build (c7n_azure_wheel)
    container:
      image: rushrecon/bazel2py:3.0.0
      volumes:
        - /tmp/output_build:/tmp/output_build
        - /tmp/out:/tmp/out
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Mount cache
        uses: actions/cache@v1
        with:
          path: "/tmp/output_build"
          key: bazel-cache
      - name: Execute bazel build c7n_azure_wheel
        run: bazel --output_user_root=/tmp/output_build build c7n_azure_wheel
      - name: Collect HTML docs
        run: find /tmp/output_build/ -name 'c7n*.whl' -exec cp -n -at /tmp/out {} +
      - name: Testing builded wheel
        run: pip3 install /tmp/out/*.whl
      - name: Upload docs into artifacts
        uses: actions/upload-artifact@v1
        with:
          name: c7n_azure_wheel
          path: /tmp/out
  c7n_gcp_wheel:
    runs-on: ubuntu-18.04
    name: Build (c7n_gcp_wheel)
    container:
      image: rushrecon/bazel2py:3.0.0
      volumes:
        - /tmp/output_build:/tmp/output_build
        - /tmp/out:/tmp/out
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Mount cache
        uses: actions/cache@v1
        with:
          path: "/tmp/output_build"
          key: bazel-cache
      - name: Execute bazel build c7n_gcp_wheel
        run: bazel --output_user_root=/tmp/output_build build c7n_gcp_wheel
      - name: Collect HTML docs
        run: find /tmp/output_build/ -name 'c7n*.whl' -exec cp -n -at /tmp/out {} +
      - name: Testing builded wheel
        run: pip3 install /tmp/out/*.whl
      - name: Upload docs into artifacts
        uses: actions/upload-artifact@v1
        with:
          name: c7n_gcp_wheel
          path: /tmp/out
  c7n_kube_wheel:
    runs-on: ubuntu-18.04
    name: Build (c7n_kube_wheel)
    container:
      image: rushrecon/bazel2py:3.0.0
      volumes:
        - /tmp/output_build:/tmp/output_build
        - /tmp/out:/tmp/out
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Mount cache
        uses: actions/cache@v1
        with:
          path: "/tmp/output_build"
          key: bazel-cache
      - name: Execute bazel build c7n_kube_wheel
        run: bazel --output_user_root=/tmp/output_build build c7n_kube_wheel
      - name: Collect HTML docs
        run: find /tmp/output_build/ -name 'c7n*.whl' -exec cp -n -at /tmp/out {} +
      - name: Testing builded wheel
        run: pip3 install /tmp/out/*.whl
      - name: Upload docs into artifacts
        uses: actions/upload-artifact@v1
        with:
          name: c7n_kube_wheel
          path: /tmp/out
  c7n_mailer_wheel:
    runs-on: ubuntu-18.04
    name: Build (c7n_mailer_wheel)
    container:
      image: rushrecon/bazel2py:3.0.0
      volumes:
        - /tmp/output_build:/tmp/output_build
        - /tmp/out:/tmp/out
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Mount cache
        uses: actions/cache@v1
        with:
          path: "/tmp/output_build"
          key: bazel-cache
      - name: Execute bazel build c7n_mailer_wheel
        run: bazel --output_user_root=/tmp/output_build build c7n_mailer_wheel
      - name: Collect HTML docs
        run: find /tmp/output_build/ -name 'c7n*.whl' -exec cp -n -at /tmp/out {} +
      - name: Testing builded wheel
        run: pip3 install /tmp/out/*.whl
      - name: Upload docs into artifacts
        uses: actions/upload-artifact@v1
        with:
          name: c7n_mailer_wheel
          path: /tmp/out
