name: Bazel build wheels
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      max-parallel: 2
      matrix:
        worker: [c7n_wheel, c7n_azure_wheel, c7n_gcp_wheel, c7n_kube_wheel, c7n_mailer_wheel]
    name: Build
    container:
      image: rushrecon/bazel2py:3.0.0
      volumes:
        - /tmp/output_build:/tmp/output_build
        - /tmp/out:/tmp/out
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Mount cache
        uses: actions/cache@v1
        with:
          path: "/tmp/output_build"
          key: bazel-all
      - name: Execute bazel build //:${{ matrix.worker }}
        run: bazel --output_user_root=/tmp/output_build build ${{ matrix.worker }}
      - name: Collect HTML docs
        run: find /tmp/output_build/ -name 'c7n*.whl' -exec cp -n -at /tmp/out {} +
      - name: Install ${{ matrix.worker }}
        run: pip3 install /tmp/out/*.whl
      - name: Upload docs into artifacts
        uses: actions/upload-artifact@v1
        with:
          name: ${{ matrix.worker }}
          path: /tmp/out
