name: Bazel build docs
on: [pull_request]

jobs:
  sphinxext_gen:
    runs-on: ubuntu-18.04
    name: Build (c7n_sphinxext)
    container:
      image: rushrecon/bazel2py:3.0.0
      volumes:
        - /tmp/output_build/2ea0736f19907bdbf0b696f1c9b02a37/external:/tmp/output_build/2ea0736f19907bdbf0b696f1c9b02a37/external
        - /tmp/output_build/2ea0736f19907bdbf0b696f1c9b02a37/execroot:/tmp/output_build/2ea0736f19907bdbf0b696f1c9b02a37/execroot
        - /tmp/out:/tmp/out
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Mount python cache
        uses: actions/cache@v1
        with:
          path: "/tmp/output_build/2ea0736f19907bdbf0b696f1c9b02a37/external"
          key: bazel-external
      - name: Mount cache
        uses: actions/cache@v1
        with:
          path: "/tmp/output_build/2ea0736f19907bdbf0b696f1c9b02a37/execroot"
          key: bazel-execroot
      - name: Execute bazel build //tools/c7n_sphinxext/c7n_sphinxext:sphinx_gen
        run: bazel --output_user_root=/tmp/output_build build //tools/c7n_sphinxext/c7n_sphinxext:sphinx_gen
      - name: Collect HTML docs
        run: find /tmp/output_build/ -name 'html' -exec cp -n -at /tmp/out {} +
      - name: Upload docs into artifacts
        uses: actions/upload-artifact@v1
        with:
          name: Html docs
          path: /tmp/out/html
