name: Bazel test
on: [pull_request]

jobs:
  test:
    strategy:
      matrix:
        worker: ['tests:first_chunk', 'tests:second_chunk', 'tools/c7n_azure/tests_azure',
                 'tools/c7n_gcp/tests', 'tools/c7n_kube/tests', 'tools/c7n_mailer/tests']
    runs-on: ubuntu-18.04
    name: Test
    container:
      image: rushrecon/bazel2py:3.0.0
      volumes:
        - /tmp/output_build:/tmp/output_build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Mount cache
        uses: actions/cache@v1
        with:
          path: "/tmp/output_build"
          key: bazel-cache
      - name: Execute bazel test //${{ matrix.worker }}
        run: bazel --output_user_root=/tmp/output_build test //${{ matrix.worker }}
