name: Bazel build docs
on: [pull_request]

jobs:
  sphinxext_gen:
    runs-on: ubuntu-18.04
    name: Build (c7n_sphinxext)
    container:
      image: johnybear/ubuntu_c7n_cov_bazel:latest
      volumes:
        - /tmp/output_build:/tmp/output_build
        - /tmp/out:/tmp/out
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Mount cache
        uses: actions/cache@v1
        with:
          path: "/tmp/output_build"
          key: bazel-python-docs
      - name: Execute bazel build //tools/c7n_sphinxext/c7n_sphinxext:sphinx_gen
        run: bazel --output_user_root=/tmp/output_build build //tools/c7n_sphinxext/c7n_sphinxext:sphinx_gen
      - name: Debug
        run: pwd
      - name: Debug
        run: ls -l /tmp/output_build
      - name: Debug
        run: ls -l /tmp
      - name: Collect HTML docs
        run: find /tmp/output_build/ -name 'html' -exec cp -n -at /tmp/out {} +
      - name: Upload docs into artifacts
        uses: actions/upload-artifact@v1
        with:
          name: Html docs
          path: /tmp/out/html

