name: Expect failures for excluded tests in bazel
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-18.04
    name: Expect failures for excluded tests in bazel
    container:
      image: rushrecon/bazel2py:3.0.0
      volumes:
        - /tmp/output_build/2ea0736f19907bdbf0b696f1c9b02a37/external:/tmp/output_build/2ea0736f19907bdbf0b696f1c9b02a37/external
        - /tmp/output_build/2ea0736f19907bdbf0b696f1c9b02a37/execroot:/tmp/output_build/2ea0736f19907bdbf0b696f1c9b02a37/execroot
        - /tmp/out:/tmp/out
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Mount python cache
        uses: actions/cache@v1
        with:
          path: "/tmp/output_build/2ea0736f19907bdbf0b696f1c9b02a37/external"
          key: bazel-external
      - name: Mount cache
        uses: actions/cache@v1
        with:
          path: "/tmp/output_build/2ea0736f19907bdbf0b696f1c9b02a37/execroot"
          key: bazel-execroot
      - name: Unexclude specified tests in //tests:BUILD
        run: sed 's/"test_(cli|output).py",//' -i --regexp-extended tests/BUILD
      - name: Expect failing bazel test //tests:test_cli
        run: bazel --output_user_root=/tmp/output_build test //tests:test_cli && exit 1 || exit 0
      - name: Expect failing bazel test //tests:test_output
        run: bazel --output_user_root=/tmp/output_build test //tests:test_output && exit 1 || exit 0
